### ISSUE TITLE
Baseline Netowork not permutation invariant

### ISSUE THREAD

**Issue by schaefes** [CMS-L1T-Jet-Tagging/TrainTagger#15]
The baseline network as it is currently implemented is not permutation invariant with regards to the jet constituents, i.e. it is not a "true" Deep Sets model. I have tested this using a single input with 128 constituents. The model output is not the same when reversing the order of the constituents. Please also check the attached image. This doesn't mean that the network is bad or unfit for the task, I just want to mention it here. 
![baseline_input_test](https://github.com/user-attachments/assets/f70f0c6c-abeb-4265-a140-db17816c5f36)

**Comment by Duchstf** [comment]
Thank you for mentioning this!! Maybe you could switch to the true DeepSet model and check as well? 

The main reason I tweaked around with the architecture was to make sure the model is small/fast enough for hardware implementation.

**Comment by Duchstf** [comment]
Hello, we changed the second layer now to kernel_size=1 in #18, again the results didn't change but we decided to stay true to DeepSet, thank you for bringing this up again!
